CREATE TABLE IF NOT EXISTS `produto_sances_raw` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL,
  `pipeline` varchar(50) COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'estoque_sances',
  `offset_pagina` int NOT NULL,
  `codigo` int NOT NULL,
  `descricao` varchar(255) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `referencia` varchar(100) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `referencia_fabrica` text COLLATE utf8mb4_0900_ai_ci,
  `endereco_setor` varchar(50) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `endereco_rua` varchar(50) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `endereco_andar` varchar(50) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `sigla_unidade_medida` varchar(10) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `descricao_unidade_medida` varchar(50) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `codigo_categoria` int DEFAULT NULL,
  `descricao_categoria` varchar(100) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `descricao_grupo` varchar(100) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `descricao_subgrupo` varchar(100) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `codigo_ean` varchar(50) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `codigo_barras` varchar(50) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ativo` tinyint(1) DEFAULT NULL,
  `data_extracao` datetime NOT NULL,
  `processado_em` datetime DEFAULT NULL,
  `criado_em` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_produto_sances_raw_pendente` (`tenant_id`,`pipeline`,`processado_em`),
  KEY `idx_produto_sances_raw_codigo` (`tenant_id`,`codigo`)
) ENGINE=InnoDB AUTO_INCREMENT=63761 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;