CREATE TABLE `quantidade_sances_raw` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL,
  `pipeline` varchar(50) COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'estoque_sances',
  `offset_pagina` int NOT NULL,
  `codigo_produto` int NOT NULL,
  `codigo_empresa` int NOT NULL,
  `cnpj` varchar(20) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `nome_razao` varchar(255) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `nome_fantasia` varchar(255) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `apelido` varchar(100) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `qtd_estoque` decimal(14,4) DEFAULT NULL,
  `qtd_aplicadas` decimal(14,4) DEFAULT NULL,
  `qtd_reservada` decimal(14,4) DEFAULT NULL,
  `qtd_transito` decimal(14,4) DEFAULT NULL,
  `qtd_pedido` decimal(14,4) DEFAULT NULL,
  `qtd_bo` decimal(14,4) DEFAULT NULL,
  `data_extracao` datetime NOT NULL,
  `processado_em` datetime DEFAULT NULL,
  `criado_em` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_quantidade_sances_raw_pendente` (`tenant_id`,`pipeline`,`processado_em`),
  KEY `idx_quantidade_sances_raw_produto` (`tenant_id`,`codigo_produto`)
) ENGINE=InnoDB AUTO_INCREMENT=828881 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;