CREATE TABLE IF NOT EXISTS `estoque_produto_bi` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL,
  `codigo_produto` int NOT NULL,
  `descricao` varchar(255) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `referencia` varchar(100) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `referencia_fabrica` text COLLATE utf8mb4_0900_ai_ci,
  `codigo_ean` varchar(50) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `codigo_barras` varchar(50) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `sigla_unidade_medida` varchar(10) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `descricao_unidade_medida` varchar(50) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `codigo_categoria` int DEFAULT NULL,
  `descricao_categoria` varchar(100) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `descricao_grupo` varchar(100) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `descricao_subgrupo` varchar(100) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `endereco_setor` varchar(50) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `endereco_rua` varchar(50) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `endereco_andar` varchar(50) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `ativo` tinyint(1) DEFAULT NULL,
  `data_processamento` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_estoque_produto_tenant_codigo` (`tenant_id`,`codigo_produto`),
  KEY `idx_produto_ultimo` (`tenant_id`,`codigo_produto`,`data_processamento`)
) ENGINE=InnoDB AUTO_INCREMENT=12936 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;