CREATE TABLE IF NOT EXISTS `estoque_empresa_bi` (
  `id` int NOT NULL AUTO_INCREMENT,
  `tenant_id` int NOT NULL,
  `codigo_produto` int NOT NULL,
  `codigo_empresa` int NOT NULL,
  `cnpj` varchar(20) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `nome_razao` varchar(255) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `nome_fantasia` varchar(255) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `apelido` varchar(100) COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `qtd_estoque` decimal(14,4) NOT NULL DEFAULT '0.0000',
  `qtd_aplicadas` decimal(14,4) NOT NULL DEFAULT '0.0000',
  `qtd_reservada` decimal(14,4) NOT NULL DEFAULT '0.0000',
  `qtd_transito` decimal(14,4) NOT NULL DEFAULT '0.0000',
  `qtd_pedido` decimal(14,4) NOT NULL DEFAULT '0.0000',
  `qtd_bo` decimal(14,4) NOT NULL DEFAULT '0.0000',
  `data_processamento` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_estoque_empresa_tenant_produto_empresa` (`tenant_id`,`codigo_produto`,`codigo_empresa`),
  KEY `idx_empresa_produto_data` (`tenant_id`,`codigo_produto`,`codigo_empresa`,`data_processamento`),
  CONSTRAINT `fk_estoque_empresa_produto` FOREIGN KEY (`tenant_id`, `codigo_produto`) REFERENCES `estoque_produto_bi` (`tenant_id`, `codigo_produto`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=121920 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;